<Button>:
    front_sise:40
    color:0.3, 0.6, 0.7, 1
    size_hint: 0.5, 0.3


<FloatLayout>:
    Button:
        pos_hint: {"x":0.25, "top":1}
        text: "Say"
    
    Button:
        pos_hint: {"x":0.25, "top":0.7}
        text: "Think"

    Button:
        id: btn
        pos_hint: {"x":0.25, "top":0.4}
        text: "Feel" if btn.state == "normal" else "Down"
        background_color: 0.3, 0.4, 0.5, 1